services:
  widget-webserver:
    image: "nginx:latest"
    ports:
      - "4300:80"
    volumes:
      - "./dist/periodic-system-select-widget/browser:/usr/share/nginx/html"
  dummy-host-webserver:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./docker/widget-dummy-host:/usr/share/nginx/html"
