services:
  periodic-system-select-webserver:
    image: "nginx:latest"
    ports: [ "4301:80" ]
    volumes: [ "./dist/periodic-system-select-widget/browser:/usr/share/nginx/html" ]
  molecule-editor-webserver:
    image: "nginx:latest"
    ports: [ "4302:80" ]
    volumes: [ "./dist/molecule-editor-widget/browser:/usr/share/nginx/html" ]
  widget-dummy-host-webserver:
    image: "nginx:latest"
    ports: [ "4400:80" ]
    volumes: [ "./docker/widget-dummy-host:/usr/share/nginx/html" ]
